background #849ab7
foreground #fffffb
cursor #fffffb
selection_background #bdd9fa
selection_foreground #fffffb
color0 #849ab7
color1 #a292af
color2 #b68d9a
color3 #b78f84
color4 #a69679
color5 #929c7d
color6 #79a190
color7 #6ea1a8
color8 #fffffb
color9 #ffffff
color10 #faffff
color11 #ecffff
color12 #ffffff
color13 #ffffff
color14 #ffffff
color15 #ffffff
