# Corners
corner-radius = 8
rounded-corners-exclude = [
  "name = 'QTILE_BAR'",
  "class_g = 'Xephyr'",
]

# Shadows
shadow = false

# Opacity
frame-opacity = 1
inactive-opacity = 1
inactive-opacity-override = false;
opacity-rule = [ "80:class_g = 'kitty'" ];

blur-method = "dual_kawase"
blur-size = 12


# General
backend = "glx"
vsync = true