# Corners
corner-radius = 8
rounded-corners-exclude = [
  "name = 'QTILE_BAR'",
  "class_g = 'Xephyr'",
]

# Shadows
shadow = false

# Opacity
frame-opacity = 1
inactive-opacity = 1
inactive-opacity-override = false;


# General
backend = "glx"
vsync = true