"$schema" = 'https://starship.rs/config-schema.json'
format = '''[│](bold grey1)$all
[└─](bold grey1) '''

add_newline = true
palette = 'nuunamnir'

[palettes.nuunamnir]
alert1 = "#84d9bd"
alert2 = "#93cfff"
alert3 = "#feb3d4"
grey1 = "#251b18"
grey2 = "#352a27"
grey3 = "#463a36"

[cmd_duration]
show_milliseconds = true
format = '[$duration](grey1)'

[package]
symbol = " "

[git_branch]
style = "purple"

[git_status]
style = "red"

[python]
symbol = " "
style = "bright-yellow"

[directory]
style = 'bold background'

[status]
format = '[│](bold grey1)[$symbol$status]($style) '

[character]
success_symbol = '[│](bold grey1)[](bold white) '
error_symbol = '[│](bold grey1)[](bold bright-white) '