"$schema" = 'https://starship.rs/config-schema.json'
format = '''[│](bold grey1)$all
[└─](bold grey1) '''

add_newline = true
palette = 'nuunamnir'

[palettes.nuunamnir]
alert1 = "#002aa7"
alert2 = "#3d006e"
alert3 = "#003260"
grey1 = "#68788e"
grey2 = "#837186"
grey3 = "#577d83"

[cmd_duration]
show_milliseconds = true
format = '[$duration](grey1)'

[package]
symbol = " "

[git_branch]
style = "bright-purple"

[git_status]
style = "bright-red"

[python]
symbol = " "
style = "bright-yellow"

[directory]
style = 'bold background'

[status]
format = '[│](bold grey1)[$symbol$status]($style) '

[character]
success_symbol = '[│](bold grey1)[](bold white) '
error_symbol = '[│](bold grey1)[](bold bright-white) '