allow_remote_control yes
enable_audio_bell no
font_family FiraMono Nerd Font Mono
font_size 4
font_features FiraMonoNFM-Regular +cv16 +ss02


# BEGIN_KITTY_THEME
# Nuunamnir
include current-theme.conf
# END_KITTY_THEME